AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'test/*.rb'
  SuggestExtensions: false
Layout/HashAlignment:
  Exclude:
    - '*.gemspec'
Metrics/AbcSize:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
