inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'test/*.rb'
  SuggestExtensions: false
Layout/HashAlignment:
  Exclude:
    - '*.gemspec'
Lint/MissingSuper:
  Exclude:
    - 'lib/tls_map/cli/cli.rb'
Metrics/AbcSize:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
